In [2]:
!pip install mtcnn
!pip install keras_applications
!pip install keras_vggface

In [3]:
import mtcnn
import keras_vggface
import matplotlib.pyplot as plt
from mtcnn.mtcnn import MTCNN
import cv2
from PIL import Image
import numpy as np
import pandas as pd
import os
import tensorflow as tf
import zipfile
import tensorflow as tf
from tensorflow.python.keras.api._v1 import keras
from tensorflow.python.keras.api._v1.keras import layers
from tensorflow.python.keras.layers.core import Dropout
from tensorflow.keras.optimizers import RMSprop
from tensorflow.keras.preprocessing.image import ImageDataGenerator
import json
import time

In [4]:
detector = MTCNN()

In [5]:
# extract all faces from a given photograph
def extract_faces(pixels, detector, required_size=(150, 150)):
    results = detector.detect_faces(pixels)
    faces_array = []
    if(len(results) > 0):
        for obj in results:
            x1, y1, width, height = obj['box']
            x2, y2 = x1 + width, y1 + height
            face = pixels[y1:y2, x1:x2]
            if(len(face) > 0 and len(face[0]) > 0):
                image = Image.fromarray(face)
                image = image.resize(required_size)
                face_array = np.asarray(image)
            faces_array.append(face_array)
    return faces_array

In [6]:
def load_images_from_folder(folder):
    images = []
    for filename in os.listdir(folder):
        img = plt.imread(os.path.join(folder,filename))
        if img is not None:
            images.append(img)
    return images

In [7]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [8]:
mask_images = load_images_from_folder('/content/drive/Shareddrives/484 fall 2020/random_stuff/input')

In [9]:
#read in images and collect all faces
output = []
for image in mask_images:
    pixels = extract_faces(image, detector)
    for obj in pixels:
        output.append(obj)

In [ ]:
#write faces to file
root = '/content/drive/Shareddrives/484 fall 2020/random_stuff/output'
counter = 0
for image in output:
    name = 'img' + str(counter) + '.jpg'
    temp = root + name
    if(len(image) > 0):
        image = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)
        cv2.imwrite(temp, np.array(image))
        counter = counter + 1

In [16]:
model = tf.keras.models.load_model('/content/drive/Shareddrives/484 fall 2020/trained/model-1606455604')

In [13]:
reshaped = []
for obj in output:
    image = cv2.cvtColor(obj, cv2.COLOR_BGR2GRAY)
    image = tf.reshape(image, [-1, 150, 150, 1])
    reshaped.append(image)

In [35]:
for obj in reshaped:
    print(model.predict(obj))

[[0. 0. 1.]]
[[0. 0. 1.]]
[[0. 0. 1.]]
[[0. 0. 1.]]
[[0. 0. 1.]]
[[0. 0. 1.]]
[[0. 0. 1.]]
[[0. 0. 1.]]
[[0. 0. 1.]]
